//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_ReportSectionDocuments
    {
        public int AMS_ReportSectionDocumentsId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
