//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Tab1_Summary
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string LandValue { get; set; }
        public string Improvements { get; set; }
        public string MarketValue { get; set; }
        public string UnitLot { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public string Purpose { get; set; }
        public string InstructedBy { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> ValuationsDate { get; set; }
        public string ValueComponent { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Client { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> ValuationApproachId { get; set; }
    }
}
