//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Tab2_Land
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string PropertyType { get; set; }
        public string PropertyIdentification { get; set; }
        public string TitleSearch { get; set; }
        public string LotNumber { get; set; }
        public string PlanNumber { get; set; }
        public string Volume { get; set; }
        public string Folio { get; set; }
        public string RegisteredProprietors { get; set; }
        public string Encumbrances { get; set; }
        public string SiteArea { get; set; }
        public string SqmHectares { get; set; }
        public string LocalGovernmentArea { get; set; }
        public string Zoning { get; set; }
        public string Overlays { get; set; }
        public string ZoningEffect { get; set; }
        public string Shops { get; set; }
        public string Transport { get; set; }
        public string Schools { get; set; }
        public string CBD { get; set; }
        public string SiteLayout { get; set; }
        public string Services { get; set; }
        public string EnvironmentalHazards { get; set; }
        public string PestInfestation { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PlanTitle { get; set; }
    }
}
