//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Tab3_BuildingImprovements
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string PropertyType { get; set; }
        public string PropertyStyle { get; set; }
        public string YearBuilt { get; set; }
        public string ExternalWalls { get; set; }
        public string Roof { get; set; }
        public string InteriorLinings { get; set; }
        public string MainFlooring { get; set; }
        public string WindowFrames { get; set; }
        public string InternalCondition { get; set; }
        public string ExternalCondition { get; set; }
        public string StreetAppeal { get; set; }
        public string PergolaVerandah { get; set; }
        public string Shedding { get; set; }
        public string Pools { get; set; }
        public string Gardens { get; set; }
        public string Fencing { get; set; }
        public string DrivewayPaving { get; set; }
        public string Outbuildings { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AncillaryImprovements { get; set; }
    }
}
