//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_ValuationCompany
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string OtherDetails { get; set; }
        public string Fax { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> Status { get; set; }
        public string ProfessionalIndemnityInsurancePolicy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> AllowJobCreate { get; set; }
        public string CompanyLogo { get; set; }
        public string BankName { get; set; }
        public string BSB { get; set; }
        public string ACNumber { get; set; }
        public string ABN { get; set; }
        public string TermsandCondition { get; set; }
        public string CertificationQualification { get; set; }
        public string FamilyLawCertification { get; set; }
        public string URL { get; set; }
        public string HeaderImage { get; set; }
        public string FooterImage { get; set; }
    }
}
