//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Tab4_RoomsFixtures
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string Rooms1 { get; set; }
        public string Rooms2 { get; set; }
        public string Rooms3 { get; set; }
        public string Rooms4 { get; set; }
        public string Bedroom { get; set; }
        public string Bathroom { get; set; }
        public string Ensuite { get; set; }
        public string Toilet { get; set; }
        public string Laundry { get; set; }
        public string Text1 { get; set; }
        public string HeatingCooling { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
