//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Valuers1
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ValuationCompanyId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EINSSN { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string CertificationType { get; set; }
        public Nullable<bool> FHACertified { get; set; }
        public Nullable<bool> VACertified { get; set; }
        public Nullable<bool> Commercial { get; set; }
        public string InsuranceCompany { get; set; }
        public Nullable<System.DateTime> InsuranceExpDate { get; set; }
        public Nullable<decimal> CoverageAmount { get; set; }
        public string AppraiserSoftware { get; set; }
        public string OtherDetails { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastLoggedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> Status { get; set; }
    }
}
