//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_Tab6_Comments
    {
        public long Id { get; set; }
        public Nullable<long> JobId { get; set; }
        public string Instructions { get; set; }
        public string Standard { get; set; }
        public string LastSaleofProperty { get; set; }
        public string Defects { get; set; }
        public string Methodology { get; set; }
        public string Closing { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
